"""
Test JARSH Chatbot with Ollama
Tests both generic PQC questions and database scan queries
"""

import asyncio
import sys
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent / "backend"))

import logging
logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


async def test_jarsh():
    """Test JARSH chatbot functionality"""
    
    print("=" * 70)
    print("  Testing JARSH Chatbot (Ollama-Powered)")
    print("=" * 70)
    print()
    
    # Import dependencies
    try:
        from engine.ai.jarsh_service import JARSHService
        from db.session import get_async_session
    except ImportError as e:
        print(f"✗ Import error: {e}")
        print("Make sure you're in the TRINETRA directory")
        return
    
    # Initialize service
    print("Initializing JARSH service...")
    jarsh = JARSHService()
    
    # Check Ollama
    if not await jarsh._check_ollama():
        print("✗ Ollama server not running")
        print("Start it with: ollama serve")
        return
    
    print("✓ Ollama server connected")
    print()
    
    # Get database session
    async for db in get_async_session():
        
        # Test cases
        test_queries = [
            {
                "query": "Hello, what can you help me with?",
                "description": "Greeting test",
                "expected_intent": "greeting"
            },
            {
                "query": "What is Post-Quantum Cryptography?",
                "description": "Generic PQC question",
                "expected_intent": "quantum_threat"
            },
            {
                "query": "Explain ML-KEM-768",
                "description": "Specific PQC algorithm question",
                "expected_intent": "quantum_threat"
            },
            {
                "query": "Show me my recent scans",
                "description": "Database query - scan history",
                "expected_intent": "scan_analysis"
            },
            {
                "query": "What vulnerabilities were found in my last scan?",
                "description": "Database query - scan analysis",
                "expected_intent": "scan_analysis"
            },
            {
                "query": "How do I migrate to PQC?",
                "description": "Mitigation planning",
                "expected_intent": "mitigation"
            },
            {
                "query": "What is my PQC readiness score?",
                "description": "Readiness assessment",
                "expected_intent": "readiness"
            }
        ]
        
        for i, test in enumerate(test_queries, 1):
            print(f"Test {i}/{len(test_queries)}: {test['description']}")
            print(f"Query: '{test['query']}'")
            print("-" * 70)
            
            try:
                result = await jarsh.get_response(
                    query=test['query'],
                    db=db
                )
                
                print(f"Intent: {result['intent']} (expected: {test['expected_intent']})")
                print(f"Confidence: {result['confidence']:.2f}")
                print(f"\nResponse:")
                print(result['response'][:400] + "..." if len(result['response']) > 400 else result['response'])
                
                if result.get('sources'):
                    print(f"\nSources: {', '.join(result['sources'])}")
                
                if result.get('suggestions'):
                    print(f"Suggestions: {', '.join(result['suggestions'][:3])}")
                
                # Check intent matches
                if result['intent'] == test['expected_intent']:
                    print("\n✓ Test passed - Intent matched")
                else:
                    print(f"\n⚠ Intent mismatch (got {result['intent']}, expected {test['expected_intent']})")
                
            except Exception as e:
                print(f"✗ Test failed: {e}")
                import traceback
                traceback.print_exc()
            
            print()
            print()
        
        break  # Exit after first session
    
    print("=" * 70)
    print("  Testing Complete")
    print("=" * 70)
    print()
    print("Key observations:")
    print("  • All responses are generated by Ollama (no hardcoded text)")
    print("  • Generic PQC questions get AI-powered answers")
    print("  • Scan queries return 'No scans found' if database is empty")
    print("  • Responses are contextual and dynamic")
    print()
    print("To populate database with scans:")
    print("  1. Start API server: cd backend && uvicorn api.main:app --reload")
    print("  2. Run scan: POST /api/scan with {\"domain\": \"example.com\"}")
    print("  3. Test again to see scan-aware responses")
    print()


if __name__ == "__main__":
    asyncio.run(test_jarsh())
